export const projects = [
  {
    slug: "ne",
    title: "LabIO",
    subtitle: "Media Art Research",
    description: `This app, developed using Next.js and hosted on Vercel, serves as a dynamic platform for a media art and choreography research project. Built with TypeScript, React, and Tailwind CSS, it provides a seamless user experience.
Sanity is used as the headless CMS, offering flexibility and ease of content management, ensuring that updates can be made efficiently. The website is designed to showcase the collaborative research projects and articles of Né Barros and João Martinho Moura.
`,
    img: "/assets/Projects/neMobile.png",
    imgUrl: "/assets/Projects/ne2.png",
    imgUrl2: "/assets/Projects/ne.png",
    technologies: [
      "Typescript",
      "Vercel",
      "Sanity",
      "React",
      "NextJS",
      "Tailwind CSS",
    ],
    githubUrl: "https://github.com/VivienIngrams/ne-joao",
    demoUrl: "https://labio.pt/",
  },
  {
    slug: "chemin-du-vivant",
    title: "Le Chemin du Vivant",
    subtitle: "Services in Geobiology",
    description: ` Le Chemin du Vivant is a professional website dedicated to geobiology and well-being services. Built with Next.js and hosted on Vercel, the site offers a clear and structured presentation of services such as habitat harmonization and radiesthesia. The website was designed with a clean and accessible interface to guide visitors through the different areas of expertise, while also explaining the process of an intervention step by step. A contact form powered by Nodemailer allows users to easily get in touch for consultations or additional information. With a focus on clarity, trust, and user experience, this platform highlights the practitioner’s holistic approach to creating harmonious living and working environments.`,
    img: "/assets/Projects/cheminMobile.png",
    imgUrl: "/assets/Projects/chemin2.jpg",
    imgUrl2: "/assets/Projects/chemin.png",
    technologies: [
      "Typescript",
      "Vercel",
      "Sanity",
      "React",
      "NextJS",
      "Tailwind CSS",
      "Nodemailer",
      "V0",
    ],
    githubUrl: "https://github.com/VivienIngrams/geo-biologie",
    demoUrl: "https://lecheminduvivant.fr/",
  },

  {
    slug: "joel",
    title: "Joël Bardeau",
    subtitle: "Photographer",
    description: `This professional portfolio website for a photographer was built with Next.js and hosted on Vercel, combining modern web development technologies with an elegant and user-friendly design. TypeScript, React, and Tailwind CSS ensure a responsive interface, delivering a smooth browsing experience.

The site is powered by Sanity as a headless CMS, allowing the photographer to manage and update content effortlessly. It showcases galleries of their work, categorized for easy navigation.

Designed with a focus on aesthetics and functionality, this website beautifully highlights the photographer’s artistic vision and serves as a key tool for connecting with their audience and clients.`,
    img: "/assets/Projects/JoelMobile.png",
    imgUrl: "/assets/Projects/joel1.png",
    imgUrl2: "/assets/Projects/joel.png",
    technologies: [
      "Typescript",
      "Vercel",
      "Sanity",
      "React",
      "NextJS",
      "Tailwind CSS",
    ],
    githubUrl: "https://github.com/VivienIngrams/joel",
    demoUrl: "https://joelbardeau.com/",
  },
  {
    slug: "photography",
    title: "2regards",
    subtitle: "Photography and Art Gallery",
    description: `The app was entirely designed for responsivity using Figma. The site is live since March 2024. The logos and favicon were made with Canva. The data is hosted in Sanity Content Lake and fully editable by the owners of the site for content updates. The vertical scrool effect is acheived with the react-horizintal-scroll package. The app was built using Next JS and is hosted on Vercel. It includes a button to subscribe to their Newsletter mailing list. Framer motion is used to smoothly animate the texts and page transitions and the splash page.`,
    img: "/assets/Projects/2regardsMobile.png",
    imgUrl: "/assets/Projects/2regards2.png",
    imgUrl2: "/assets/Projects/2regards.png",
    technologies: [
      "Figma",
      "Sanity",
      "Canva",
      "React",
      "NextJS",
      "Tailwind CSS",
      "Typescript",
      "Vercel",
    ],
    githubUrl: "https://github.com/VivienIngrams/2regards",
    demoUrl: "https://2regards.net",
    designUrl:
      "https://www.figma.com/file/stff81bEWbHdr8KgWwGetb/2regards?type=design",
  },
  {
    slug: "geobiologie",
    title: "Joëlle Villegas",
    subtitle: "Geobiologist",
    description: `This app was built in April 2025 with Next.js and hosted on Vercel. The app includes a contact form using Nodemailer to send messages directly from the website to the owner.`,
    img: "/assets/Projects/Joelle.png",
    imgUrl: "/assets/Projects/JoelleSite.png",
    imgUrl2: "/assets/Projects/JoelleSite.png",
    technologies: ["React", "NextJS", "Tailwind CSS", "Typescript", "Vercel"],
    githubUrl: "https://github.com/VivienIngrams/Geo-biologie",
    demoUrl: "https://lecheminduvivant.vercel.app",
  },
  {
    slug: "mathilde",
    title: "Mathilde Cudeville",
    subtitle: "Photographer",
    description: `Built in September 2024 with Next.js and hosted on Vercel, this app showcases the artistic projects of the French photographer Mathilde Cudeville. Sanity is used as a headless CMS. The app was designed on Figma.`,
    img: "/assets/Projects/MathildeMobile.png",
    imgUrl: "/assets/Projects/mathilde.png",
    imgUrl2: "/assets/Projects/mathilde1.png",
    technologies: [
      "Typescript",
      "Vercel",
      "Sanity",
      "Figma",
      "React",
      "NextJS",
      "Tailwind CSS",
    ],
    githubUrl: "https://github.com/VivienIngrams/Mathilde",
    demoUrl: "https://mathildecudeville.com/",
    designUrl:
      "https://www.figma.com/file/stff81bEWbHdr8KgWwGetb/2regards?type=design&node-id=503%3A441&mode=design&t=SPvNx0u1ND4oCBST-1",
  },
  {
    slug: "model-portfolio",
    title: "Sakiko Oishi",
    subtitle: "Model Portfolio",
    description: `Built in July 2023 with Next.js and hosted on Netlify, this web application connects with a MongoDB Cluster to store data. The Firebase SDK is integrated for user authentication, allowing authorized administrators to sign in using their email address and password, creating a secure environment for efficient data management. With input forms, authorized users can manage and manipulate data, enabling easy additions, updates, and deletions.`,
    img: "/assets/Projects/KikoMobile.png",
    imgUrl: "/assets/Projects/KikoSiteBook.png",
    imgUrl2: "/assets/Projects/KikoSite.png",
    technologies: [
      "React",
      "NextJS",
      "Tailwind CSS",
      "Typescript",
      "Netlify",
      "MongoDB",
      "Firebase",
    ],
    githubUrl: "https://github.com/VivienIngrams/Sakiko",
    demoUrl: "https://sakiko-oishi.vercel.app/",
  },
  {
    slug: "psychologist",
    title: "Marta Guimaraes",
    subtitle: "Psychologist and Coach",
    description: `Published in February 2024, this app was entirely designed for responsivity using Figma. The logos and favicon were made with Canva. The app was built using Next JS and is hosted on Vercel. A Contact form uses Nodemailer to send messages directly from the website to the owner. Framer motion is used to smoothly animate the texts.`,
    img: "/assets/Projects/MartaMobile.png",
    imgUrl: "/assets/Projects/Marta1.png",
    imgUrl2: "/assets/Projects/Marta.png",
    technologies: [
      "Figma",
      "Canva",
      "React",
      "NextJS",
      "Tailwind CSS",
      "Typescript",
      "Vercel",
    ],
    githubUrl: "https://github.com/VivienIngrams/Marta",
    demoUrl: "https://martaguimaraes.vercel.app",
    designUrl:
      "https://www.figma.com/file/oTmhGdpyNQcQfarDel5v17/Marta?type=design",
  },

  {
    slug: "landing-page",
    title: "Banhos e Tosquias",
    subtitle: "Business Landing Page",
    description: `This is a landing page for a local animal grooming service in Porto. This user-friendly SPA is built with React, Next.js, and TypeScript. It includes Google Maps for simple navigation and a contact form for reaching out using Nodemailer. Framer Motion is used to add some subtle style and animation, while Tailwind CSS ensures a clean and modern look. The site is hosted since November 2023 on Netlify for reliable access.`,
    img: "/assets/Projects/LandingSiteMobile.png",
    imgUrl: "/assets/Projects/LandingSite.png",
    imgUrl2: "/assets/Projects/LandingPage.png",
    technologies: [
      "React",
      "NextJS",
      "Nodemailer",
      "Netlify",
      "Google Map API",
      "Framer Motion",
      "Tailwind CSS",
      "Typescript",
    ],
    githubUrl: "https://github.com/VivienIngrams/Landing-Page",
    demoUrl: "https://tosquias.netlify.app",
  },
  {
    slug: "art-facilitation",
    title: "Celeste Burr Herrera",
    subtitle: "Art Facilitation",
    description: `This website, developed using WordPress, Elementor, and CSS, serves as a platform for an art facilitator since April 2023. It seamlessly blends aesthetics with functionality, providing a canvas for the artist's work and their exploration of the profound connections between art, health, culture, and human relationships through various mediums. The site has since recreated from scratch using Vercel for hosting and Sanity as a headless content management system for easy content updates.`,
    img: "/assets/Projects/CelesteMobile.png",
    imgUrl: "/assets/Projects/CelesteSite.png",
    imgUrl2: "/assets/Projects/CelesteSiteWorkshops.png",
    technologies: ["Wordpress", "Elementor", "CSS", "HTML", "Vercel", "Sanity"],
    githubUrl: "https://github.com/VivienIngrams",
    demoUrl: "https://celesteburrherrera.com",
  },
  {
    slug: "bombarda",
    title: "Bombarda",
    subtitle: "Creative Quarter, Porto",
    description: `Built in June 2024 with Next.js and hosted on Vercel, this app brings together all of the places of interest in the Bombarda Art District in Porto, Portugal. For ease of use and organisation, the places are separated into three categories: Art, Food and Drink, and Shops. It is also possible to filter through the different options with tags so that users can find what they are interested in. The main page also displays a random selection to help users discover new places in the neighbourhood. Sanity is used as a headless CMS. The app was designed on Figma.`,
    img: "/assets/Projects/BombardaMobile.png",
    imgUrl: "/assets/Projects/bombarda.png",
    imgUrl2: "/assets/Projects/bombarda.png",
    technologies: [
      "Typescript",
      "Vercel",
      "Sanity",
      "Figma",
      "React",
      "NextJS",
      "Tailwind CSS",
    ],
    githubUrl: "https://github.com/VivienIngrams/Bombarda",
    demoUrl: "https://bombarda-app.vercel.app/",
    designUrl:
      "https://www.figma.com/design/NgxKSrPCzHglqWXHGAgRxd/Bombarda-Digital-Lab?node-id=1625-3626&t=J5jfEZI2K7L9M6rZ-1",
  },
  {
    slug: "research-blog",
    title: "Alex Ingrams",
    subtitle: "Transparency and technology in public policy",
    description: `This app was built in September 2023 using Next JS and hosted on Vercel. The data is stored in Firebase realtime database. User authentication is available through the Firebase SDK. This enable authorised administrators to sign in with an email address. Input forms in turn enable authorized users to add, update and delete blog data.`,
    img: "/assets/Projects/AlexMobile.png",
    imgUrl: "/assets/Projects/AlexSiteResearch1.png",
    imgUrl2: "/assets/Projects/AlexSiteResearch1.png",
    technologies: [
      "React",
      "NextJS",
      "Tailwind CSS",
      "Javascript",
      "Firebase",
      "Vercel",
    ],
    githubUrl: "https://github.com/VivienIngrams/AlexIngrams",
    demoUrl: "https://alex-ingrams.vercel.app",
  },
];
